### PR TITLE
Add html decoding/encoding to collections/

### PR DESCRIPTION
**Pull request by DonRichards**
Addresses the issues in https://jhulibraries.atlassian.net/browse/LAGS-90

### CODE REVIEW

**Review by jabrah — COMMENTED** [review]
Looks like a nice simple change to the Handlebars template in the items list.

I'm curious what changes went into the build artifacts for `mirador`, `stimulus`, and `styles`? Are those just some weird build-system oddity, like line endings or similar - or were there code changes that forced changes in those artifacts?

**Comment by DonRichards** [comment]
@jabrah Yes, that's mostly all oddities caused by the build process. The only change I made was to list-item.ts

**Comment by DonRichards** [comment]
@jabrah There was one style/ID I added to debug and left it in by mistake. Thanks for asking about it. I missed this when reviewing my code commit. Line 66 in js/packages/glimmer-idc/src/components/list-item.ts is the only change I made; the rest was from the compile process.

**Comment by jabrah** [comment]
To me it looks good to merge. Right now, I'm not too sure about PR workflows since the project has been passed around. If you or someone else is able to do the merge that's fine with me, if I need to merge that's also OK with me @DonRichards

**Pull request merged**
