### PR TITLE
Contact page

### PR DESCRIPTION
**Pull request by jabrah**
This website contact form appears at `http://islandora-idc.traefik.me/contact`

Please make sure to (re)build the styling assets:

```
cd js/
yarn && yarn build
```

This will build all assets and put them in a place where Drupal can find them. You can then clear Drupal's cache to see the changes.

Closes https://github.com/jhu-idc/iDC-general/issues/103

### CODE REVIEW

**Comment by jabrah** [comment]
TODO:
* Get the image to display on the right side of the page
* Try to move the checkbox and submit button to right side of the form
* Try to change the field labels (not sure if this is feasible)

image

**Comment by jabrah** [comment]
I avoided touching any lower level templates as much as possible, explicitly defining only the contact page template. The form template and anything lower level is untouched, although I did add a bit of CSS customization to some of the form elements (button style in main.css and some rules in form.css). 

One question: Should I add a known unique ID/class to sort of namespace form styles on this page?

**Review by jaredgalanis — APPROVED** [review]
Seems good for now. Things to consider:

1) Are we going to add the section divider at the page center (see design)?
2) What do you think about adding the padding so that the entire contact container is a card with a bit of drop shadow and with the main page background being not white?

**Comment by jabrah** [comment]
Added `html--contact.html.twig` to fully customize and cardify the contact page

image

**Comment by jabrah** [comment]
Future changes (not this PR) will attempt to sidestep Drupal's default templating system to fully customize the contact form, inputs, labels, etc

**Review by jaredgalanis — APPROVED** [review]
💥  looks great!

**Pull request merged**
